version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dass
      POSTGRES_DB: meubanco
      TZ: America/Sao_Paulo # Opcional, mas recomendado manter o banco no mesmo fuso
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    restart: on-failure
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: dass
      DB_DATABASE: meubanco
      DB_PORT: 5432
      PORT: 3000
      TZ: America/Sao_Paulo # 📌 FORÇA O FUSO HORÁRIO DE BRASÍLIA NO NODE.JS
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "5170:5173"  # ou 80 se estiver servindo build estático
    depends_on:
      - backend

volumes:
  pgdata: