BEGIN;

CREATE SCHEMA checklist_app;

CREATE TABLE checklist_app.marcas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255),
  "ultimaAlteracao" timestamp without time zone DEFAULT now()
);

CREATE TABLE checklist_app.setores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL,
  ativo integer NOT NULL DEFAULT 1
);

CREATE TABLE checklist_app.unidades (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL,
  ativo integer NOT NULL DEFAULT 1
);

CREATE TABLE checklist_app.turnos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(50) NOT NULL,
  entrada_inicio time without time zone NOT NULL,
  entrada_fim time without time zone NOT NULL,
  intervalo_inicio time without time zone NOT NULL,
  intervalo_fim time without time zone NOT NULL
);

CREATE TABLE checklist_app.celulas_producao (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL,
  id_setor_fk integer REFERENCES checklist_app.setores(id),
  ativo integer NOT NULL DEFAULT 1,
  id_marca_fk integer REFERENCES checklist_app.marcas(id)
);

CREATE TABLE checklist_app.modelo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255),
  data_criacao timestamp without time zone NOT NULL DEFAULT now(),
  marca varchar(255),
  id_marca_fk integer REFERENCES checklist_app.marcas(id),
  ativo boolean NOT NULL DEFAULT true,
  id_setor_fk integer REFERENCES checklist_app.setores(id) ON UPDATE CASCADE
);

CREATE TABLE checklist_app.categorias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_modelo integer REFERENCES checklist_app.modelo(id) ON UPDATE CASCADE ON DELETE CASCADE,
  categoria varchar(255),
  ctq boolean NOT NULL DEFAULT false
);

CREATE TABLE checklist_app.perguntas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria integer REFERENCES checklist_app.categorias(id) ON UPDATE CASCADE ON DELETE CASCADE,
  id_modelo integer REFERENCES checklist_app.modelo(id) ON UPDATE CASCADE ON DELETE CASCADE,
  pergunta text,
  identificacao varchar(100),
  ativo smallint NOT NULL DEFAULT 1
);

CREATE TABLE checklist_app.usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar,
  "codBar" varchar(255),
  ativo smallint NOT NULL DEFAULT 1,
  funcao varchar(255),
  nivelusuario smallint,
  id_setor_fk integer REFERENCES checklist_app.setores(id),
  id_celula_fk integer REFERENCES checklist_app.celulas_producao(id),
  id_unidade_fk integer REFERENCES checklist_app.unidades(id),
  id_turno_fk integer REFERENCES checklist_app.turnos(id),
  matricula varchar(64) NOT NULL,
  papel varchar(16) NOT NULL CHECK (papel IN ('ADMIN', 'LIDER', 'INSPETOR'))
);

CREATE UNIQUE INDEX usuarios_matricula_unique
  ON checklist_app.usuarios (matricula);

CREATE INDEX marcas_nome_idx ON checklist_app.marcas (nome);
CREATE INDEX setores_ativo_nome_idx ON checklist_app.setores (ativo, nome);
CREATE INDEX unidades_ativo_nome_idx ON checklist_app.unidades (ativo, nome);
CREATE INDEX celulas_setor_marca_ativo_idx
  ON checklist_app.celulas_producao (id_setor_fk, id_marca_fk, ativo);
CREATE INDEX celulas_ativo_nome_idx
  ON checklist_app.celulas_producao (ativo, nome);
CREATE INDEX modelo_setor_marca_ativo_idx
  ON checklist_app.modelo (id_setor_fk, id_marca_fk, ativo);
CREATE INDEX modelo_ativo_nome_idx
  ON checklist_app.modelo (ativo, nome);
CREATE INDEX modelo_id_marca_fk_idx
  ON checklist_app.modelo (id_marca_fk);
CREATE INDEX categorias_modelo_idx ON checklist_app.categorias (id_modelo);
CREATE INDEX perguntas_modelo_ativo_idx ON checklist_app.perguntas (id_modelo, ativo);

CREATE TABLE checklist_app.formulario_submissoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer REFERENCES checklist_app.usuarios(id),
  id_modelo integer REFERENCES checklist_app.modelo(id),
  id_celula integer REFERENCES checklist_app.celulas_producao(id),
  assinatura bytea,
  respostas jsonb NOT NULL,
  snapshot jsonb,
  inicio_checklist timestamp without time zone,
  data_envio timestamp without time zone NOT NULL DEFAULT now(),
  id_setor integer REFERENCES checklist_app.setores(id),
  assinatura_path text
);

CREATE INDEX formulario_submissoes_data_envio_idx
  ON checklist_app.formulario_submissoes (data_envio DESC);
CREATE INDEX formulario_submissoes_usuario_data_idx
  ON checklist_app.formulario_submissoes (id_usuario, data_envio DESC);
CREATE INDEX formulario_submissoes_modelo_idx
  ON checklist_app.formulario_submissoes (id_modelo);
CREATE INDEX formulario_submissoes_setor_idx
  ON checklist_app.formulario_submissoes (id_setor);
CREATE INDEX formulario_submissoes_celula_data_idx
  ON checklist_app.formulario_submissoes (id_celula, data_envio DESC);

COMMIT;
