BEGIN;

CREATE SCHEMA checklist_app;

CREATE TABLE checklist_app.marcas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255),
  "ultimaAlteracao" timestamp without time zone DEFAULT now()
);

CREATE TABLE checklist_app.setores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL,
  ativo integer NOT NULL DEFAULT 1
);

CREATE TABLE checklist_app.unidades (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL
);

CREATE TABLE checklist_app.turnos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(50) NOT NULL,
  entrada_inicio time without time zone NOT NULL,
  entrada_fim time without time zone NOT NULL,
  intervalo_inicio time without time zone NOT NULL,
  intervalo_fim time without time zone NOT NULL
);

CREATE TABLE checklist_app.celulas_producao (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL,
  id_setor_fk integer REFERENCES checklist_app.setores(id),
  ativo integer NOT NULL DEFAULT 1,
  id_marca_fk integer REFERENCES checklist_app.marcas(id)
);

CREATE TABLE checklist_app.modelo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255),
  data_criacao timestamp without time zone NOT NULL DEFAULT now(),
  marca varchar(255),
  ativo boolean NOT NULL DEFAULT true,
  id_setor_fk integer REFERENCES checklist_app.setores(id) ON UPDATE CASCADE
);

CREATE TABLE checklist_app.categorias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_modelo integer REFERENCES checklist_app.modelo(id) ON UPDATE CASCADE,
  categoria varchar(255),
  ctq boolean NOT NULL DEFAULT false
);

CREATE TABLE checklist_app.perguntas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria integer REFERENCES checklist_app.categorias(id) ON UPDATE CASCADE ON DELETE CASCADE,
  id_modelo integer REFERENCES checklist_app.modelo(id) ON UPDATE CASCADE ON DELETE CASCADE,
  pergunta text,
  identificacao varchar(100),
  ativo smallint NOT NULL DEFAULT 1
);

CREATE TABLE checklist_app.usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar,
  "codBar" varchar(255),
  ativo smallint NOT NULL DEFAULT 1,
  funcao varchar(255),
  nivelusuario smallint,
  id_setor_fk integer REFERENCES checklist_app.setores(id),
  id_celula_fk integer REFERENCES checklist_app.celulas_producao(id),
  id_unidade_fk integer REFERENCES checklist_app.unidades(id),
  id_turno_fk integer REFERENCES checklist_app.turnos(id),
  matricula varchar(64) NOT NULL,
  papel varchar(16) NOT NULL CHECK (papel IN ('ADMIN', 'LIDER', 'INSPETOR'))
);

CREATE UNIQUE INDEX usuarios_matricula_unique
  ON checklist_app.usuarios (matricula);

CREATE TABLE checklist_app.formulario_submissoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer REFERENCES checklist_app.usuarios(id),
  id_modelo integer REFERENCES checklist_app.modelo(id),
  id_celula integer REFERENCES checklist_app.celulas_producao(id),
  assinatura bytea,
  respostas jsonb NOT NULL,
  snapshot jsonb,
  inicio_checklist timestamp without time zone,
  data_envio timestamp without time zone NOT NULL DEFAULT now(),
  id_setor integer,
  assinatura_path text
);

COMMIT;
