CREATE TABLE IF NOT EXISTS checklist_app.categorias_padrao (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL,
  ctq boolean NOT NULL DEFAULT false,
  perguntas jsonb NOT NULL DEFAULT '[]'::jsonb,
  ativo integer NOT NULL DEFAULT 1,
  "ultimaAlteracao" timestamp without time zone DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS categorias_padrao_nome_unique_idx
  ON checklist_app.categorias_padrao (LOWER(TRIM(nome)))
  WHERE ativo = 1;
