CREATE TABLE checklist_app.formulario_evidencias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_submissao integer NOT NULL REFERENCES checklist_app.formulario_submissoes(id),
  id_pergunta integer NOT NULL,
  mime varchar(32) NOT NULL CHECK (mime IN ('image/jpeg', 'image/png', 'image/webp')),
  tamanho integer NOT NULL CHECK (tamanho > 0),
  conteudo bytea,
  criada_em timestamp with time zone NOT NULL DEFAULT now(),
  expira_em timestamp with time zone NOT NULL DEFAULT (now() + interval '6 months'),
  removida_em timestamp with time zone
);

CREATE UNIQUE INDEX formulario_evidencias_submissao_pergunta_uidx
  ON checklist_app.formulario_evidencias (id_submissao, id_pergunta);
CREATE INDEX formulario_evidencias_expiracao_idx
  ON checklist_app.formulario_evidencias (expira_em, removida_em);
